### ISSUE TITLE
Error (?(

### ISSUE THREAD

**Issue by kirax-12** [AbilSeno/spamallforone#1]
Ini kenapa ya kalo gini dan cara fix nya gmana

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 622, in <module>
    main.main()
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 16, in main
    main.start()
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 62, in start
    spam.ruparupa(nom)
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 323, in ruparupa
    c = json.loads(b)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kirax-12** [comment]
Cuma beberapa doang yg masuk sms aja
Selebih nya muncul error itu

**Comment by Fazax22** [comment]
Biasa nya dri file nya kk

**Comment by Fazax22** [comment]
Coba cek lagi

**Comment by Shootblack** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 622, in <module>
    main.main()
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 30, in main
    main.main()
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 16, in main
    main.start()
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 44, in start
    spam.mypoin(nom)
  File "/data/data/com.termux/files/home/spamallforone/brutal.py", line 139, in mypoin
    e = r.post(otp,headers=uatp,data={"phone":"62"+nom,"csrfmiddlewaretoken": c["value"]}).text
TypeError: 'NoneType' object is not subscriptable



Error' brother

**Comment by sniperpakidulan** [comment]
bner min... eLoL malahan kagak ada yg masuk @AbilSeno
